### https://medium.com/@philipp.schmiedel/local-docker-mysql-macos-fa7ac14348c4
### Missing the download of MySQL Docker image?

version: '3.3'

services:
    php:
        build: .
        env_file:
            - .env.local
        volumes:
            - ./:/var/www
        ports:
            - "8000:80"

###> doctrine/doctrine-bundle ###
    database:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'flavour_tracker'
            MYSQL_ROOT_PASSWORD: 'test'
            MYSQL_ROOT_HOST: '%'
        volumes:
            - ./db-data:/var/lib/mysql
        ports:
            - '3306:3306'
        # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
        # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
    mailer:
        image: schickling/mailcatcher
        ports: ["1025", "1080"]
###< symfony/mailer ###

volumes:
    ###> doctrine/doctrine-bundle ###
    db-data:
###< doctrine/doctrine-bundle ###
